# 第一階段：編譯
# 使用 --platform=$BUILDPLATFORM 讓編譯器跑在宿主機速度（Mac ARM）
FROM golang:1.24-alpine AS builder

ARG TARGETOS
ARG TARGETARCH

WORKDIR /app



# 複製 Go module 檔案並下載依賴 (利用 Docker cache)
COPY go.mod go.sum .
RUN go mod download

COPY api/ ./api/

RUN ls -R

# 執行跨平台編譯：這會產出正確的 Linux ELF 格式
# CGO_ENABLED=0 確保 100% 靜態編譯
RUN CGO_ENABLED=0 go build -o /app/main ./api/main.go

# 第二階段：運行 (最小化 Image)
FROM alpine:latest
RUN apk add --no-cache ca-certificates

WORKDIR /app
COPY --from=builder /app/main .

EXPOSE 8080
ENTRYPOINT ["./main", "server"]